global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "demo-service"
    static_configs:
      - targets: ["app:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # метрики контейнерів (CPU/mem/network per container)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # метрики хоста (CPU/mem/disk/load)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
